[programs.localnet]
monaco_protocol = "E3iPA3DuYoUa2kbH7enBXpPu3s5a7WCfJVg1F83Mghnv"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn runJestTests"

[[test.genesis]]
address = "F56JTFUQa2Gao3fCtTZmUUkTdmVYypGmRp1kkYeJ4Da7"
program = "tests/anchor/protocol_product/protocol_product.so"
