[toolchain]
anchor_version = "0.29.0"
solana_version = "1.17.30"

[programs.localnet]
monaco_protocol = "7i2N9qqqcfne1BouHhMw1vvNAo2aeVwwWhecWy5XrKqY"

[programs.devnet]
monaco_protocol = "7i2N9qqqcfne1BouHhMw1vvNAo2aeVwwWhecWy5XrKqY"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn runJestTests"

[[test.genesis]]
address = "2cTEcEM1B5pkVFrqSFnUDowgbRvqc5uoagRBAQ1Uehh7"
program = "tests/anchor/protocol_product/protocol_product.so"
